version: "3"
services:
  node:
    build: ./node
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
    volumes:
      - ./node/api:/app/api
  db:
    command: --default-authentication-plugin=mysql_native_password
    build: ./db
    ports:
      - "3307:3306"
